### ISSUE TITLE
Update the samples using `/edits` api in the `ai.text:Client`

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-guides/ai-samples#70]
**Description:**
Currently there are two samples implemented to showcase the usage of the `/edits` api endpoint in OpenAI. But this API have been [deprecated](https://platform.openai.com/docs/deprecations/edit-models-endpoint) and shutdown its operation. So the given samples are not working. Below are those samples.
- [Write robust API powered AI applications](https://ballerina.io/usecases/ai/#write-robust-api-powered-ai-applications).
- [Bring text alive with openai chat (Sample 2)](https://ballerina.io/usecases/ai/#bring-text-alive-with-openai-chat). 

Both the samples are pointed to a single [sample ballerina code](https://github.com/ballerina-guides/ai-samples/blob/main/correct_grammar_and_spelling_in_text_using_openai/main.bal). We need to update this sample once [issue](https://github.com/ballerina-platform/ballerina-library/issues/6024) is fixed from the library team.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by xlight05** [comment]
Closing as per https://github.com/ballerina-guides/ai-samples/pull/71
